
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- oauth2-proxy-ns.yaml
- ../../base/oauth2-proxy
namespace: oauth2-proxy

secretGenerator:
  - name: oauth2-proxy-secrets
    envs:
    - secrets/oauth2-proxy-secrets.sct

